#!/usr/bin/env bash

##
## A consistent pass entry multi selection menu.
##

## [2014-2016]  [Jason A. Donenfeld]
## [2016-2017]  [Ampling]

## DEPENDENCIES;  pass, dmenu, xclip
## (optional)     libnotify, xdotool

shopt -s nullglob globstar failglob
set -euo pipefail

x_selection=${PASSWORD_STORE_X_SELECTION:-clipboard}
prefix=${PASSWORD_STORE_DIR:-$HOME/.password-store}
version=passmuster-0.5.2

arg1=${1:-}
arg2=${2:-}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#$prefix/}" )
password_files=( "${password_files[@]%.gpg}" )
cleanup=False
selection=''
before=''
my_name=${0##*/}
userID=$(id -u "$(whoami)")
usage="$my_name [help] [kill] [version] [clip] [quiet] [dmenu...]"


## Check for optional dependency, libnotify.
{ hash notify-send &>/dev/null && notifyit=0 ;} ||
{ printf '%s\n' "w: libnotify not found" && notifyit=1 ;}


_notify () {
  message=$1
  [[ $notifyit -eq 0 ]] && notify-send "$message" --icon=dialog-password
  [[ $notifyit -le 1 ]] && printf '%s\n' "$message"
}

_clear () {
  ## Removes old filelock(s).
  umask 077
  stalelock=${stalelock:-''}
  stalelock=$(find /tmp -maxdepth 1 -name "$my_name.$userID.*" -user "$(whoami)" -print -quit -type d) &&
  if [[ -n "$stalelock" ]]; then
    stalename=${stalelock%.*}
    report=$(pgrep -fa "$my_name" | grep bash | sed 's/\s.*$//')
    stalePID=$(printf '%s' "$stalename" | sed -e "s/\/tmp\/$my_name\.[0-9]\{1,6\}\?\..*\.//g")
    [[ $report == *"$stalePID"* ]] &&
    {
    parentID=$(ps -o pid= --ppid "$stalePID" )
    kill "$parentID" &>/dev/null || _notify "e: Unable to kill old process"
    } || exit 1
    rmdir /tmp/passmuster."$userID".* &>/dev/null || _notify "e: Unable to clear old filelock"
  fi
}

_finish () {
  [[ $cleanup == True ]] &&
  printf '%s' "$before" | base64 -d | xclip -sel "$x_selection" -i &>/dev/null &&
  compgen -G /tmp/passmuster."$userID"* &>/dev/null &&
  rmdir /tmp/passmuster.*.*."$$".lock &>/dev/null
  exit 0
}


hash xclip &>/dev/null || { _notify "e: xclip not found. Please install xclip."; exit ;}
{ hash xdotool &>/dev/null && clipit=0 ;} || { _notify "w: xdotool not found."; clipit=0 ;}
## Check for unwanted x-selection events caused by Qupzilla issue.
pgrep -fa 'qupzilla' &>/dev/null && _notify "w: qupzilla is known to break our xclip loop."
[[ ! -e "$prefix" ]] && { _notify "e: $prefix not found." && exit ;}

[[ $arg1 == *v* || $arg2 == *v* ]] && { _notify "$version" && exit ;}
[[ $arg1 == *h* || $arg2 == *h* ]] && { printf '%s\n' "$usage" && exit ;}
[[ $arg1 == *k* || $arg2 == *k* ]] && { _notify "clean and exit."; _clear; exit ;}
[[ $arg1 == *c* || $arg2 == *c* ]] && { clipit=1 && shift ;}
{
[[ $arg1 == *qq* || $arg2 == *qq* ]] && { notifyit=2 && shift ;} ;} || {
[[ $arg1 == *q* || $arg2 == *q* ]] && { notifyit=1 && shift ;}
}

## Runs the _finish funtion on exit.
trap _finish EXIT

## dmenu exits on KeyPress not KeyRelease. Effects roundcube issue.
## (It might be nice to send KeyRelease event to some dummy window.) 
for selection in $(printf '%s\n' "${password_files[@]}" | dmenu -f "$@"); do
  passel+=("$selection")
done

_clear; [[ -n $selection ]] || exit 1

## Add filelock
( mktemp -d "/tmp/passmuster.$userID.XXXXXXXXXX.$$.lock" &>/dev/null ||
{ _notify "e: Unable to make filelock."; exit 1 ;} )

## Avoid setting bash variables to null.
before=$(xclip -sel "$x_selection" -o | base64) || true
cleanup=True
round=0


[[ $clipit -eq 0 ]] && {
## AUTOTYPE
for entry in "${passel[@]}"; do
  pass "$entry" | sed '1!d' | tr -d '\n' | 
  tee $(xclip -i -l 1 -quiet -sel "$x_selection" &>/dev/null) |
  xdotool type --delay --clearmodifiers --file -
  _notify "${passel[$round]} sent via autotype"
  round=$((round + 1))
done
}
[[ $clipit -eq 1 ]] && {
## CLIPBOARD
for entry in "${passel[@]}"; do
  pass "$entry" | sed '1!d' | tr -d '\n' |
  xclip -l 1 -quiet -sel "$x_selection" &>/dev/null
  _notify "${passel[$round]} sent via $x_selection"
  round=$((round + 1))
done
}
