#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

X_SELECTION="$PASSWORD_STORE_X_SELECTION"
prefix=${PASSWORD_STORE_DIR-~/.password-store}

password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

if [[ $typeit -eq 0 ]]; then
    for password in $(printf '%s\n' "${password_files[@]}" | 
	dmenu -f "$@"); do
	pass show $password | 
	    xclip -l 1 -quiet -sel $X_SELECTION
    done

[[ -n $password ]] || exit

else
    pass show "$password" | { read -r pass; printf %s "$pass"; } |
	xdotool type --clearmodifiers --file -
fi
